requirements.txt, satip/download.py, setup.py
Moves the download code from https://github.com/openclimatefix/nowcasting_dataset/pull/172 into Satip to be more widely useful. Leaves the Click functionality in `nowcasting-dataset`
Fixes #
Downloading, deleting random files, and rerunning the script.
=> Add download script for EUMETSAT data

satip/intermediate.py, satip/utils.py
Only calculate OSGB coordinates once, at it wakes awhile, and Xarray doesn't check coordinates when appending to a Zarr store.
Fixes #59 
=> Add only calculating OSGB coordinates once

satip/compression.py, satip/utils.py
Renames coordinates to be more explicit
Fixes #62
Test plots run, which run the whole pipeline
=> Rename coordinates to be more explicit

satip/utils.py
Fixes #61
Saves the attributes for each channel with the channel name prepended to the final data array
Fixes #61
Test plots plot
=> Add saving attributes for all channels

README.md, environment.yml, setup.py
Very simple little PR :slightly_smiling_face:  Just:
* adding `environment.yml`
* update `README.md` with instructions to install using conda
* added `Jack Kelly` to authors :slightly_smiling_face: 
I installed in a fresh conda environment using the new instructions in the README.
`py.test` runs and tests pass.
=> added environment.yml and updated README with conda instructions

.github/workflows/plotting.yaml, scripts/generate_test_plots.py
Adds more plots to the CI action, this time in the full RSS extant
Fixes #
Test generation script
=> Add plotting geostationary

satip/utils.py
=> add logging

requirements.txt, satip/__init__.py, satip/app.py, satip/utils.py, setup.py
add function to save to the lastest-data-table. This save a datestamp to the a sql table, so we know when this service last ran
Fixes #103 
normal unittest, function is test in datamodel
=> nowcasting_datamodel==0.0.36, and save to last data table

docs/requirements.txt
Fixes the doc creation
Fixes #
=> Fix for doc creation

satip/__init__.py, satip/app.py, scripts/process_eumetsat_data_to_individual_zips.py, scripts/process_monthly_zarrs.py
Hi, I'd like to start contributing. I just went for an easy issue to address (#101) to start out. I only removed one unnecessary line of code, following one of the suggestions made in the issue.
=> remove unused version in __init__.py #101

satip/app.py, satip/eumetsat.py, tests/test_app.py
Allows manually running the data tailor cleanup option in the app
Fixes #
Unit test
=> Run data tailor cleanup option

satip/app.py, satip/data_store.py, satip/eumetsat.py, satip/utils.py
small change to save as .net files
Fixes #
=> save as .net files

satip/data_store.py
Change filename for raw
raw names for 15mins with not have .nat in them
=> update raw name

.flake8, .pre-commit-config.yaml, .ruff.toml, scripts/convert_native_to_zarr_modal.py, scripts/generate_test_plots.py, scripts/modal_processing.py, scripts/process_eumetsat_data_to_individual_zips.py, scripts/process_monthly_zarrs.py, scripts/read_and_combine_satellite.py
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes #
=> Change to ruff

satip/eumetsat.py
Created in response to broken forecaster incident. See details in https://app.asana.com/0/1201681902047911/1204124272110550/f
=> Update totalResults field path in OpenSearch API response JSON

satip/app.py, satip/utils.py
Also small refactor to make name of function more pythonic
Checks each dataset when using the Data Tailor to see if its already been downloaded, before starting. This should hopefully reduce how long it takes to download the 15 minute data, and reduce duplication of work.
Fixes #189 
Unit tests
=> Add checking datasets before each tailored download

satip/utils.py
Update return of quality filter to explicitly return True if the data is fine.
Fixes #
=> Update data quality check

.github/workflows/plots.yml, requirements.txt, satip/download_manager.py, scripts/generate_test_plots.py, tests/test_utils.py
Updated data test plotting scripts and created a new workflow for them
Fixes #231 
pytest
=> Updated data test plotting scripts 

requirements.txt, satip/app.py
Remove updating data table
Helps with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/337
CI tests
=> remove nowcasting saving to db

satip/utils.py
Fix a folder checking, move from os to fsspec
CI tests, and tested local
=> use fsspec to check is path exists and is directory

requirements.txt
Pin back requests
Fixes #268
Ci tests pass
=> requests==2.31.0 #268

satip/app.py
Dont check native file
#273 
CI tests
=> dont check native dir

satip/app.py, satip/download.py, satip/filenames.py, satip/geospatial.py, satip/utils.py, tests/integration_test/test_integration_app.py, tests/integration_test/test_integration_download.py, tests/integration_test/test_integration_eumetsat.py, tests/unit_test/test_filenames.py
Add option for IODC satellite pull
Main changes are in app.py, other changes are small refactoring and small changes needed for IODC
Refactor `use_backup` to `use_hr_serviri` in many places
#279 
Example of image - 
and windy.com weather roughly at the same time 
Q: do we see this white band in the satellite image that we trained on?
Im trying to work out the right balance of re-writing lots of things, and get this working. Have discussed with @devsjc about re-writing this consumer completely
CI + extra tests
=> IDOC Satellite #minor

satip/utils.py
Fix for non hrv filename
Helps with #293 
CI tests
=> remove hrv from filename

satip/filenames.py, tests/unit_test/test_filenames.py
Dont remove hrv from file name
CI tests
=> dont remove hrv from file name

satip/filenames.py, satip/utils.py, tests/unit_test/test_filenames.py
- put back in UTC
- Add UTC to time from eumetset file
- add option not to strip hrv
Fixes #
=> put utc back in, add option to strip hrv or not

satip/eumetsat.py
Remove data tailor HRV for the moment
Half fixes #305 
Tested the app locally, + CI tests
=> Fix data tailor

requirements.txt, satip/app.py
I have scanned through the repository and have commented out all the extra requirements. Please review and then I will be sure and remove all the extra requirements.
=> Reduced requirements

satip/eumetsat.py
Break if customization has failed
CI tests wont pass due to 5 min satellite being down right now
=> break when customaization has failed

satip/eumetsat.py
1. if there are any failed tasks, lets try to clean them up
This app is hard to make changes for, but this feels like atleast we will delete "FAILED" customatizations for the queue
Ci wont pass, as 5 mins data is not there now
=> clean up failed if inactive

satip/eumetsat.py
=> move up to 3 attemps

satip/eumetsat.py
Make better error message
Ci tests not working
=> raise from exception
