openclimatefix/Satip

- .bumpversion.cfg
- .github/workflows/linters.yaml
- .github/workflows/workflows.yaml
- requirements.txt
- satip/compression.py
- satip/download.py
- satip/eumetsat.py
- satip/intermediate.py
- satip/utils.py
- scripts/cloudmask.py
- scripts/get_raw_eumetsat_data.py
- setup.py
Adds saving cloud mask data into the intermediate Zarr, for the non-HRV channels, as that is what the cloud mask resolution matches.
Probably will put the cloud masks in their own Zarr file, as they might have a different availability than the native files. Some days seem to be missing half of the cloud masks, but none of the native files, for example.
Whats left to do:
Fixes #39 
> Add cloud masks to intermediate Zarr

- .flake8
- satip/compression.py
- satip/geospatial.py
- satip/serialize.py
- satip/utils.py
* Fix the OSGB coordinates issue: Use the original `x` and `y` geostationary coordinates as the 'main' coordinates. Also add a 2D `x_osgb` coordinate, and a 2D `y_osgb` coordinate.
* Serialize the `dataarray.attrs` in a way that makes all the information easy to recover from the Zarr.
* Fix the ordering of the GEOGRAPHIC_BOUNDS.
`py.test` runs and the GitHub actions CI tests pass.  (Well, the linting doesn't pass, but that'll be fixed separately in issue #54)
> Fix coordinates

- Dockerfile
- requirements.txt
- satip/app.py
- satip/eumetsat.py
- satip/utils.py
- tests/test_app.py
The pods in AWS keep running out of memory, trying to process the whole area in multiple timesteps, so this makes each file its own NetCDF file that is saved instead to make it simpler and lower memory usage.
Fixes #86 
> Reduce memory consumption of app.py

- satip/utils.py
- scripts/convert_old_to_new_zarr.py
- tests/test_app.py
Seeing the pre-commit hook fail for styling reasons, I thought a quick fix could make that prettier.
For the failing hooks, see here: https://results.pre-commit.ci/run/github/309434883/1652613955.8tjARYTKTTyC5_OLMi-uOQ .
Only naming and comments changed. Local tests were run, no additional tests were needed.
Due to me not having any old zarr-files on my machine, I could not run the script.
> Fixed flake8 and pydocstyle errors for convert_old_to_new_zarr.py

- README.md
- satip/app.py
- satip/utils.py
- tests/test_app.py
To keep the live data matching the v15 dataset the models were trained on as much as possible, this gives an option to rescale the data or not, by default leaving the dataast as the native values.
Fixes #112 
Unit tests
> Do not rescale data by default

- satip/utils.py
Adds back the exact same compression as used for v15 dataset, I think, which should fix the issue of live not matching training data
Fixes #112 
> Add back old compression to match v15 dataset

- satip/app.py
- satip/intermediate.py
IF there are no files to download, the app will exit early, so latest/hrv_latest and the database update all don't happen.
Fixes #115 
> Stop app if no files to download

- satip/app.py
- satip/download.py
- satip/intermediate.py
- satip/utils.py
When RSS imagery isn't available, 15-minutely data should be still available, so try downloading that. Uses a different save name to ensure not accidentally loading 15 minute data when expecting 5 minute data
Fixes #106 
Unit Tests
> Add 15 minutely fallback option

- satip/eumetsat.py
Adds a step if there is any error in the data tailor customization download, it will cleanup all data tailor customizations that are done or failed.
Fixes #
Unit tests
> Add cleaning up data tailor if error

- satip/app.py
- satip/eumetsat.py
- satip/utils.py
Fixed a couple of `bare except:` issues. There may be a tighter exception that could be used though. Then ran `black --line-length 100 satip` which removed a few blank lines.
Fixes #137 
CI tests.
> Fix linting errors

- .github/workflows/release.yaml
This is to make sure that the new workflow (1.2.0) is backward compatible (unlike 1.1.0).
> Bump python-docker-release workflow to 1.2.0

- satip/eumetsat.py
- tests/test_eumetsat.py
The regex for getting the datetime from the filename breaks when there is a filename like:
`MSG4-SEVI-MSG15-0000-NA-20230814075918.739000000Z-NA`
where the `0100-NA` string in most RSS imagery is replaced by `0000-NA`. This fixes that
Fixes #
> Fix regex for 0000-NA filenames

- README.md
The readme states to run the following command to download the last 2 hours of RSS imagery, but this fails as save-dr is not a known argument. 
`python satip/app.py --api-key=<EUMETSAT API Key> --api-secret=<EUMETSAT API Secret> --save-dr="/path/to/saving/files/" --history="2 hours"`
Fixes #
From app.py, it looks like this should be `--save-dir`, which I've updated (but might be "--save-dir-native"?). I've updated README.md to correct this
I re-ran the command with --save-dir which was recognised by app.py
N/A
The default checklist relates to code changes are not applicable as this is a documentation change
- NA My code follows [OCF's coding style …
> correct typo in readme

- satip/app.py
- satip/eumetsat.py
- tests/test_eumetsat.py
Trying to speed up download_tailored_datasets by adding an option to parallel downloads using `concurrent.futures`
Fixes https://github.com/openclimatefix/Satip/issues/144
With parallelization:
Tested with `test_data_tailor_parallel`, a new test I added in test_eumetsat.py. Parallelization reduces the test time from `18:10` to `07:41`.
> speed up download_tailored_datasets by adding option to parallel downloads

- satip/download.py
Fixes https://github.com/openclimatefix/Satip/issues/157
remove sleep command left on accident, which improves downloading time
Discussions: https://github.com/openclimatefix/Satip/issues/157#issuecomment-2023223214
> Remove sleep command left on accident

- satip/app.py
- satip/utils.py
…ries
This change adds a function to utils.py that checks whether a provided path leads to a directory or just a file
The aforementioned function is then added to the top of app.py to check whether save_dir and/or save_dir_native are valid paths
I want to add this change because this will save resources in case you input a bad path. Otherwise the script proceeds to make expensive API calls to EUMETSAT etc. to then fail at the very end when it tries pushing files to the provided save_dir and/or save_dir_native paths.
This has not been put on the issues page
The following list shows the 3 save_dir paths that been given as arguments and their results after this PR's changes:
1. A save_dir path that leads to a directory, satip continues executing
2. A save_dir path that leads to a file, satip …
> Add input validation of directory paths given to satip

- satip/goes_download_manager.py
- tests/test_goes_download_manager.py
This PR adds a new function `download_archival_goes_data` to the `GOESDownloadManager` class. This function allows users to download archival GOES data from NOAA's CLASS archive.
> Extend GOES data retrieval to include NOAA's CLAss archive

- satip/utils.py
Add try and except around moving a file.
An error happens if another satellite consumer, has already moved it
CI tests
> try and except around file move

- requirements.txt
- satip/app.py
Switch over to 15 minutes data, if less than 1 hour and 30 hour of 5 min data. Currently it only swicthes if there is no data
#286 , 
We do this by checking if there is 75% of the "history" data we need. In live history is set to 120 minutes
had to pin flex-parser - https://github.com/hgrecco/flexparser/issues/12
CI tests
> switch to 15 mintues data, if less than 1.5 hour of 5 min data

- satip/filenames.py
- tests/unit_test/test_filenames.py
Fix for 1st pull of 15 minute data. This makes sure it dont get confused by 5 minute data, and not download the new 15 min data
#313 
CI tests
> dont remove 15 minutes timestamp

- satip/utils.py
In the GCP archive, the bits of the image which are off the earth disk are filled with NaNs. There are even times when some random scattered pixels over the earth are NaNs, (probably just a measurements error from the satellite). In the production data, there are no NaNs and the pieces of the image off the earth disk are all zeros.
This is an issue for the cloudcasting model. When training, all the pixels that are NaN are flagged to the model so it knows where they are. This isn't possible in production since all NaNs are now zero, but not all the zero values were NaN - at night the visual channels go dark, for instance.
This PR updates the type of the dataset to float32, which implements NaN.
> Allow NaNs in datasets

- satip/eumetsat.py
If the data taylor customisation failed twice, then fail the consumer. This will stop gaps appearing in the data. 
no tested, very hard too. CI test will fail as 5 min data is down right now
> raise error if 2 failed attemps
